import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "../components/MainNav.jsx";
import PageTransition from "../components/PageTransition.jsx";
import ReactangleTransition from "@/components/ReactangleTransition";
import Gradient from "@/components/Gradient";
import Header from "@/components/Header.jsx";

const SometypeMono = Sometype_Mono({
  variable: "--font-Sometype-Mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${SometypeMono.variable} antialiased overflow-hidden relative`}>
        <Gradient />
        <ReactangleTransition />
        <PageTransition>
          <div className="flex ">
            <div className="hidden 2xl:flex w-[285px] h-screen bg-[#140e25]">
              <MainNav />
            </div>
            <div className="w-full max-w-[1130px] px-[15px] mx-auto ">
             <Header />
              <div>{children}</div>
            </div>
          </div>
        </PageTransition>
      </body>
    </html>
  );
}
